name: CI

on: [push]

env:
  SSH_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEAwVEz0zCiL9bmE0m0ALIqqZrYWdUClSlmMzbrnDN+BLe/Zps1
hJUdZnT1tC+JAMRid+5g0l4GLGXzKaUUy9FeBPaPC/fd5MqoZvd+u45XCGcnDQAA
eNs5TNw4kgWFH1Dum05xiQ/mzJ7LE9s6AGeWJ6cLPxWzA2fS4GU0qlwAL4KX/i1q
KFtqQ0YxGsTkLeOWabGp9RAbbXzFjpDXf4MhX0XeP+BPSzIMkj+oGOm4Cq1FYtwM
HO51D9H+y6e5evMRpwOVuA/ShJ/NOyw2MVmYytj1Yq7USrDcq1deqEyR625qj91L
nh5yi/45z/s3FltSN8+5s2fmt3RDQChv5rSFyAugTbB5CR8wtoh5SUKd0u/nFe4s
ZAJzbyBMD5i29+DuxG/TTabOOlTVHhmBge6O91R6GAOHaclrCUSti7W9k1b5/t76
bmotadQtUOWSF3Mo2qNZMpouRWqJidT0BwYOgIkQe3RwzAdQ9S4TQi8fozfZbDEa
8AMJoCQ6j3HOuXLul78auabgYUlk7NLlDyTHVnEgekEtXDBkW8vyz4gFVC5Xi0pZ
bn0J/SgCVoGFn42+q+AMVLrNKy8ChIC+2LXxwgxkkgPnLZdho8gmcokIzp5mUmgj
I/h7AkIlViVnyV8qfnYomkdbo73+ctNa3r2KaYBxucS1lvDEruXrggtVaU8CAwEA
AQKCAgAUqldlwvlWL4eugH6qDmG/ehVDsSDSt4y8en6rAYQoq/My3EesfHuamXPZ
8bTtweXxgn2ThMft1MOEQaicoIKHpEsmu+CwFbaf3zg12OGr58mwZZN8rUQNrS2s
9RhwgGh+w17MCJ5Nucc6wFY4dy+sMyVhdofe8X6E92dZs3ZfndBytFcjU6EN6lco
e0DAjmePX+sruS+Sv4z85bXrudBbohk/7yd61zGp1qfjwI7929z4KaQahFE7l4wV
0usMiNHBGVcsHcuNhZRdDX0I6dY1ZQZXqMR6luKCvIHFcFNZqBbjJIRyCuOIMe1A
iE8wvXgSDaDWhrZkCR0r+Bv858e0gGhVJgqyjAYASPW25IjF2PPVDskyPfxlH48S
kfVIdVoySx/WcuPqFNxBWJ7GYvgH2tqGuKrraqFJCsQQ/ZlSvaAR9uSdMCMZnMLQ
rDlQgthjC6uqRhz6rkdTHkfMtzprxUAQ6AlwZziICMBe4CrU2OV5sTOH8mJ08QF0
AO/y/ZNEY99+7FSPF52cXoRKWyxyJNCQRe6jPbLx92ZMPPAVi/7HQVoPuMRPpNkq
fMzpYmdK42fT7ySJjOFImGBukkyUxAOCs+BaxcYAXi1p6EQ739OCotoSxoKpXyn8
rXlB7uHRrIDNJ/n4PttiZo0itwsO2752WjUHwMP/rpspuCK3dQKCAQEA5/cmQCEJ
Z7ye6N+rxu++ghj9cJtLdJQpOWRAD74/hF+TWtZNwABMvxii9bWEVzdRQgyajEAq
54+pw1sE7cHTtLTWyDvk+C8Kpy6XDtXCCxTgEgeyJ7HNAEuxmf2/HEs7RFtcjBAV
OAEtns4ax2qKedOkiZF55LAPxnOIhCy0+kGxk7o8dfPmAEh+O+BGUNLzfuCFlgEs
k60to77+iRrQ3N8WlpNF83Lzdr7c6ShzucThd7A6zc7XFRCihwWPJr3GGSa4AGVn
zTS6O+FYF9pXVCH//niXdjApkcmgHkDPg3IXu3TJP/Aq8tPSyV60j0r2m+zw5h0r
fB64ncq/4kREFQKCAQEA1VjqAw+3tF0wJmM3leqdP5YaMpAv/RLSgdtBD4biyWpU
J9td986a6DDbQmOvIoetFHQ3jMPtLMChhtkoj3Fql7wntN3NAzcZP1wJJkq8xm/J
L78KnFQcv6ZbCX6gq48XEXiJQai9EhxmUeKANeHe+Y92i5fdhTp5UpAvT16aHKTD
j10AL0eyYH1n/Vb7YjpjLizwZLyuUvBIHnXuqI7Wmrq52F7WBzLKe59NZ/s11Ch3
mTtE2zxQMDqOurIYxMwI7+A2qt/rzMQTwJeoj8kXDqeM4iPnI8NedakLK3uBOa6s
WjqifW+9MUaIddJ8c8TuNRkc9l6dBl1QfEPym+Mc0wKCAQBkAeMk3NlwNxsP7Xbi
wvQQpPOHe/yRG1uWmckgwHYj/QzLqf9FWxu7e8SuSH7xFzFaV5K+CuA0i3S2e+Rp
GRrMGvdKxr/V3HosT+Lii3goTOy5+UVu5bIrgXblnEerzCeWNgl1fW2YgrGHePaE
qUNgeMXEZcr2tI1okuD1k0zHZFFKDo4IkInF73s1F2FZcUl3lxcg8Aqm9I/ru+mD
dOM9hpT3gDE1X4bl2C3n+//AxMgsUPdZSebi9xQLQHNSUZk5uL61tQKGr0fnjyTq
y8DAzhPPQ3CRjPwvFY2J3YlZ83OV5yjo/wOVQ4vqM4GHEdu2p/XIUCUyUxBnP0Vx
KNttAoIBAQDSsovxWA1x5/JMhwH3YYvIp2HZ+8IY6gTRUApx3iGNDyBreF7WA8nC
c7WmXDIzJNEO+TN/JmPOJbOgLEi9WSIPFjgUjFQSz9B0XV1/3qGOTAnhyIcfGoaF
0zHnL5JXu+npTCQpnw6Sm0+FoO5DyHzf9An8FJAmKjh1DIZcmS4UCbhElnE/QExu
tIsFjGiZetZGXQVQR3LV4A0pYAjBmMdiafRuNkKjO0rzScE1Zsejbg+nWfxHk8oR
x1L8GDUT7fkJhWIX4SrLv/1N37kNv2exBlHBZ/m2vRRFmRu55rAZmmMGfQ/KV5b9
2g2cZrKX1q317IZI3emvxmpdPvGTeHkXAoIBAQCIWvUTE1xMggl/gyokqEvIxfDu
LVtgp6UDnEzUAyyToZaT8mxgqjRyrjmCBtQTIWiXk3TMP9K2yb7F6uCRHWLJktpu
12kBtTPmeO6bRQhKCrZ/0EFSk7NidhnwPHdXxJPieCMO2PsfqkCQHF1tydiGxdWp
jv3xvxRfhavfe/K4BAOsbM48YmAn6r/owwz1mLgaNJepSblbYrzGYI6z/plR7p8g
R9wgOlzIgDOHKDKLhqDpFQE1Ds6EqylSayXtxWNX2kBir/Sdo0ARZ0TzT+nvrk+t
as1wRASGHToJsVBkZsiUWVw7OQ3Uxg10pe7pFdoao+5+lZTvBLHsDjVEMi7t
-----END RSA PRIVATE KEY-----
  REMOTE_HOST: davidspiv.com
  REMOTE_USER: ubuntu
  REMOTE_TARGET: /var/www/davidspivack.com/portfolio/dist/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/src/, /node_modules/, .eslintrc.js, CNAME, .gitignore, package.json, pnpm-lock.yaml"
